### PR TITLE
Add new config server service name

### PR DESCRIPTION
**Pull request by glammers1**
Hi @adamkl 

I have noticed that in Spring Cloud Services v3.0.0 there had been some changes related to the Config Server. One of them affects the use of this project because there is a new service name for the SCS Config Server service called `p.config-server` instead of the one which uses the library at this moment `p-config-server`. This PR aims to allow both. It would be great if you can review it and create a new release.

More info: https://content.pivotal.io/blog/spring-cloud-services-3-0-includes-new-and-improved-config-server

By the way, regarding #19 I can confirm, based on my tests, that at runtime that reference is replaced with the raw credentials and everything works fine.

### CODE REVIEW

**Comment by adamkl** [comment]
Hey @glammers1, thanks for another pull request!

To be honest, I don’t have much access to PCF these days (my new employer doesn’t use Cloud Foundry), so it’s going to be tough for me to properly maintain this library. 

Would you be willing help out? If so, I can give you contributor access to this repo, and you can handle the merges/releases without me being a bottle neck. 

Think about it, and in the mean time I’ll try to push this PR through in the next day or two.

**Comment by glammers1** [comment]
Hi @adamkl 

Sounds like a plan! I am using Cloud Foundry in a project along with this library as a config client for Nodejs. If I could release new versions faster, it would avoid using my fork as a dependency (there are some constraints on the project and this is not a good practice). I think that this library should not change much more in a short time, but just in case, it would be great if I had contributor access.

It would really help me out if you can release a new version by tomorrow. 

Thank you very much!

**Comment by adamkl** [comment]
Not sure why Travis hasn't reported back the status of the CI build. I checked manually and everything looks good, so I'll merge this.

**Comment by adamkl** [comment]
@glammers1 Finally added you as a collaborator, sorry for taking so long!

**Pull request merged**
